movies/movieapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name='movieapp'

urlpatterns = [

    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/<int:id>/',views.add,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

movies/movies/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

movies/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    image=models.ImageField(upload_to='gallery')

    def __str__(self):
        return  self.name

movies/movieapp/forms.py
from .models import Movie
from django import forms

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name','desc','year','image']

movies/movieapp/views.py
# Create your views here.
from django.shortcuts import render, redirect
from .models import Movie
from .forms import MovieForm


def index(request):
    movie=Movie.objects.all

    context={
        'movie_list':movie
    }
    return render(request,'index.html',context)

def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)

    return render(request,'detail.html',{'movie':movie})

def add(request,id):
    movie=Movie.objects.get(id=id)
    if request.method == "POST":
        name=request.POST.get('name')
        desc=request.POST.get('desc')
        year=request.POST.get('year')
        image=request.FILES['image']
        movie=Movie(name=name,desc=desc,year=year,image=image)
        movie.save(id=id)
        return redirect('/')
    return render(request,'add.html',{'movie':movie})

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'movie':movie,'forms':form})

def delete(request,id):
    if request.method == 'POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movies/templates/add.html
{% extends 'base.html' %}
{% block body %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter Name"><br>
    <input type="text" name="desc" placeholder="Enter Description"><br>
    <input type="text" name="year" placeholder="Enter Year"><br>
    <input type="file" name="image" ><br>
    <input type="submit">


</form>
{% endblock %}

movies/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    ONLINE MOVIE STORE
  </a>

</nav>
{% block body %}
{% endblock %}

</body>
</html>

movies/templates/delete.html
<form method="POST">
    {% csrf_token %}
    Are you sure you want to delete?
    <input type="submit">

</form>

movies/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.image.url}}" height="200" width="200">
        </div>

        <div class="col-md-6">
        <h2>{{movie.name}}</h2>
        <h6>{{movie.desc}}</h6>
        <h3>{{movie.year}}</h3>
        <a class="btn btn-warning"  href="{% url 'movieapp:update' movie.id %}">Update</a>
        <a class="btn btn-danger"  href="{% url 'movieapp:delete' movie.id %}">Delete</a>
        <a class="btn btn-danger" href="{% url 'movieapp:add_movie' movie.id %}">Add Movie</a>

        </div>

    </div>

</div>


{% endblock %}

movies/templates/edit.html
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{forms.as_p}}
  <input type="submit">
</form>

movies/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col=md-3">
            <div class="card" style="width: 18rem; height:400px;">
  <img class="card-img-top" src="{{i.image.url}}" alt="Card image cap"  height="250px" width="350px">
  <div class="card-body" >
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.price}}</p>
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">View Details</a>
  </div>
</div>

        </div>
        {% endfor %}


    </div>
</div>
{% endblock %}